language: objective-c
osx_image: xcode9.2

xcode_project: BXSwiftUtils.xcodeproj

before_install:
- gem install xcpretty

matrix:
    include:
        - env: SCHEME="BXSwiftUtils-macOS" DESTINATION="platform=macOS,arch=x86_64"
        - env: SCHEME="BXSwiftUtils-iOS" DESTINATION="platform=iOS Simulator,name=iPhone X,OS=11.2"

script: set -o pipefail; xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" build test | xcpretty
